# Generated by Django 5.2.4 on 2025-09-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=8, unique=True)),
                ('tipo', models.CharField(choices=[('instructor', 'Instructor'), ('aprendiz', 'Aprendiz'), ('administrativo', 'Administrativo'), ('visitante', 'Visitante'), ('restringido', 'Restringido')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('areas_permitidas', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(choices=[('sistemas', 'Laboratorio de Sistemas'), ('quimica', 'Laboratorio de Química Aplicada'), ('carbones', 'Laboratorio de Carbones'), ('biotecnologia', 'Laboratorio de Biotecnología'), ('beneficios', 'Lab. Beneficios Minerales'), ('aguas', 'Laboratorio de Aguas'), ('suelos', 'Laboratorio de Suelos'), ('abc_maquinaria', 'Ambiente ABC - Maquinaria Pesada'), ('bilinguismo', 'Ambiente de Bilingüismo'), ('minas_didacticas', 'Minas Didácticas')], max_length=50)),
                ('metodo', models.CharField(choices=[('carnet_manual', 'Carnet Manual'), ('reconocimiento_facial', 'Reconocimiento Facial'), ('tarjeta_rfid', 'Tarjeta RFID'), ('huella_digital', 'Huella Digital')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('acceso_permitido', models.BooleanField(default=False)),
                ('razon_denegacion', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.usuario')),
            ],
        ),
    ]
