# Generated by Django 5.2.3 on 2025-09-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("carnet", models.CharField(max_length=8, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("instructor", "Instructor"),
                            ("aprendiz", "Aprendiz"),
                            ("administrativo", "Administrativo"),
                            ("visitante", "Visitante"),
                            ("restringido", "Restringido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("areas_permitidas", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Acceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratorio",
                    models.CharField(default="Laboratorio X", max_length=50),
                ),
                ("metodo", models.CharField(default="manual", max_length=30)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accesos.usuario",
                    ),
                ),
            ],
        ),
    ]
