# Generated by Django 5.2.4 on 2025-09-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
        ('usuarios', '0004_alter_registro_options_remove_usuario_carnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.RenameField(
            model_name='acceso',
            old_name='laboratorio',
            new_name='ambiente',
        ),
        migrations.AlterField(
            model_name='acceso',
            name='metodo',
            field=models.CharField(choices=[('carnet_manual', 'Carnet Manual'), ('reconocimiento_facial', 'Reconocimiento Facial')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
