# Generated by Django 5.2.4 on 2025-09-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=8, unique=True)),
                ('tipo', models.CharField(choices=[('instructor', 'Instructor'), ('aprendiz', 'Aprendiz'), ('administrativo', 'Administrativo'), ('visitante', 'Visitante'), ('restringido', 'Restringido')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('areas_permitidas', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='acceso',
            name='metodo',
            field=models.CharField(default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='laboratorio',
            field=models.CharField(default='Laboratorio X', max_length=50),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.usuario'),
        ),
    ]
