# Generated by Django 5.2.4 on 2025-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_alter_acceso_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceso',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Acceso', 'verbose_name_plural': 'Accesos'},
        ),
        migrations.AddField(
            model_name='acceso',
            name='confianza',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='metodo',
            field=models.CharField(choices=[('manual', 'Acceso Manual'), ('reconocimiento_facial', 'Reconocimiento Facial'), ('huella_dactilar', 'Huella Dactilar'), ('tarjeta_rfid', 'Tarjeta RFID')], max_length=30),
        ),
    ]
