# Generated by Django 5.2.6 on 2025-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_usuario_remove_acceso_tipo_acceso_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='acceso_permitido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceso',
            name='razon_denegacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='laboratorio',
            field=models.CharField(choices=[('sistemas', 'Laboratorio de Sistemas'), ('quimica', 'Laboratorio de Química Aplicada'), ('carbones', 'Laboratorio de Carbones'), ('biotecnologia', 'Laboratorio de Biotecnología'), ('beneficios', 'Lab. Beneficios Minerales'), ('aguas', 'Laboratorio de Aguas'), ('suelos', 'Laboratorio de Suelos'), ('abc_maquinaria', 'Ambiente ABC - Maquinaria Pesada'), ('bilinguismo', 'Ambiente de Bilingüismo'), ('minas_didacticas', 'Minas Didácticas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='metodo',
            field=models.CharField(choices=[('carnet_manual', 'Carnet Manual'), ('reconocimiento_facial', 'Reconocimiento Facial'), ('tarjeta_rfid', 'Tarjeta RFID'), ('huella_digital', 'Huella Digital')], max_length=30),
        ),
    ]
