# Generated by Django 5.2.3 on 2025-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carnet", models.CharField(max_length=8, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("instructor", "Instructor"),
                            ("aprendiz", "Aprendiz"),
                            ("administrativo", "Administrativo"),
                            ("visitante", "Visitante"),
                            ("restringido", "Restringido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
