# Generated by Django 5.2.4 on 2025-09-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("cc", "Cédula de Ciudadanía"),
                            ("ce", "Cédula de Extranjería"),
                            ("pa", "Pasaporte"),
                            ("ti", "Tarjeta de Identidad"),
                        ],
                        default="cc",
                        max_length=2,
                        verbose_name="Tipo de Identificación",
                    ),
                ),
                (
                    "numero_identificacion",
                    models.CharField(
                        max_length=10,
                        null=True,
                        verbose_name="Número de Identificación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre Completo"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("instructor", "Instructor"),
                            ("aprendiz", "Aprendiz"),
                            ("administrativo", "Administrativo"),
                            ("visitante", "Visitante"),
                            ("restringido", "Restringido"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Usuario",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Usuario Activo"),
                ),
                (
                    "face_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="faces/users/",
                        verbose_name="Imagen Facial",
                    ),
                ),
                (
                    "face_encoding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Codificación Facial (JSON)"
                    ),
                ),
                (
                    "face_registered",
                    models.BooleanField(
                        default=False, verbose_name="Rostro Registrado"
                    ),
                ),
                (
                    "ambientes_permitidos",
                    models.TextField(
                        blank=True,
                        default="sistemas",
                        help_text="Códigos de ambientes separados por coma (ej: sistemas,quimica,carbones). Escribe 'todos' para acceso total.",
                        verbose_name="Ambientes Permitidos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Entrada", "Entrada"), ("Salida", "Salida")],
                        max_length=10,
                        verbose_name="Tipo de Acceso",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("facial", "Reconocimiento Facial"),
                            ("manual", "Acceso Manual"),
                            ("carnet", "Tarjeta/Carnet"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Método de Acceso",
                    ),
                ),
                (
                    "ambiente",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Ambiente/Laboratorio",
                    ),
                ),
                (
                    "confianza",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nivel de Confianza"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Acceso",
                "verbose_name_plural": "Registros de Acceso",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
