# Generated by Django 4.2.7 on 2025-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='ambientes_directos',
            field=models.ManyToManyField(blank=True, help_text='Ambientes a los que este usuario tiene acceso directo', related_name='usuarios_permitidos', to='ambientes.ambiente', verbose_name='Ambientes Permitidos (Nuevo Sistema)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group', verbose_name='Grupos de Permisos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ambientes_permitidos',
            field=models.TextField(blank=True, default='sistemas', help_text="Códigos de ambientes separados por coma. Escribe 'todos' para acceso total.", verbose_name='Ambientes Permitidos (Legacy)'),
        ),
    ]
