# Generated by Django 4.2.7 on 2025-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_ambiente_activo'),
        ('usuarios', '0002_alter_usuario_options_usuario_ambientes_directos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ambientes_directos',
            field=models.ManyToManyField(blank=True, help_text='Ambientes a los que este usuario tiene acceso directo.', related_name='usuarios_permitidos', to='ambientes.ambiente', verbose_name='Ambientes Permitidos (Nuevo Sistema)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(max_length=15, null=True, verbose_name='Número de Identificación'),
        ),
    ]
