# Generated by Django 4.2.7 on 2025-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ambiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='confianza',
            field=models.FloatField(blank=True, null=True, verbose_name='Confianza del Reconocimiento'),
        ),
        migrations.AddField(
            model_name='registro',
            name='metodo',
            field=models.CharField(choices=[('facial', 'Reconocimiento Facial'), ('manual', 'Acceso Manual'), ('carnet', 'Tarjeta/Carnet')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='face_encoding',
            field=models.TextField(blank=True, null=True, verbose_name='Codificación Facial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/users/', verbose_name='Imagen Facial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='face_registered',
            field=models.BooleanField(default=False, verbose_name='Rostro Registrado'),
        ),
    ]
