# Generated by Django 5.2.5 on 2025-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_ambiente_activo'),
        ('usuarios', '0003_alter_usuario_ambientes_directos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='ambiente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ambiente/Laboratorio'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='confianza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nivel de Confianza (%)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ambientes_directos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_directos', to='ambientes.ambiente', verbose_name='Ambientes Permitidos (Nuevo Sistema)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ambientes_permitidos',
            field=models.TextField(blank=True, default='', help_text="Códigos de ambientes separados por coma. Escribe 'todos' para acceso total.", verbose_name='Ambientes Permitidos (Legacy)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación'),
        ),
    ]
