# Generated by Django 4.2.7 on 2025-09-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_registro_ambiente_registro_confianza_registro_metodo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Registro de Acceso', 'verbose_name_plural': 'Registros de Acceso'},
        ),
        migrations.AlterField(
            model_name='registro',
            name='ambiente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ambiente/Laboratorio'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='confianza',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel de Confianza'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='metodo',
            field=models.CharField(choices=[('facial', 'Reconocimiento Facial'), ('manual', 'Acceso Manual'), ('carnet', 'Tarjeta/Carnet')], default='manual', max_length=20, verbose_name='Método de Acceso'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10, verbose_name='Tipo de Acceso'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Usuario Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carnet',
            field=models.CharField(max_length=8, unique=True, verbose_name='Número de Carnet'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='face_encoding',
            field=models.TextField(blank=True, null=True, verbose_name='Codificación Facial (JSON)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('aprendiz', 'Aprendiz'), ('administrativo', 'Administrativo'), ('visitante', 'Visitante'), ('restringido', 'Restringido')], max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
