# Generated by Django 5.2.4 on 2025-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_registro_options_remove_usuario_carnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ambientes_permitidos',
            field=models.TextField(blank=True, default='sistemas', help_text="Códigos de ambientes separados por coma (ej: sistemas,quimica,carbones). Escribe 'todos' para acceso total.", verbose_name='Ambientes Permitidos'),
        ),
    ]
