# Generated by Django 4.2.7 on 2025-09-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_registro_options_alter_registro_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carnet',
            field=models.IntegerField(unique=True, verbose_name='Número de Carnet'),
        ),
    ]
