# Generated by Django 4.2.24 on 2025-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_registro_ambiente_alter_registro_confianza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de Identificación'),
        ),
    ]
