# Generated by Django 4.2.7 on 2025-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_carnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='carnet',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pa', 'Pasaporte'), ('ti', 'Tarjeta de Identidad')], default='cc', max_length=2, verbose_name='Tipo de Identificación'),
        ),
    ]
