# Generated by Django 5.2.4 on 2025-09-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(default="000", max_length=50, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Ocupado", "Ocupado"),
                            ("Mantenimiento", "Mantenimiento"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
                ("capacidad", models.IntegerField(default=1)),
                (
                    "riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                            ("muy_alto", "Muy Alto"),
                        ],
                        default="bajo",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TareaProtocolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProtocoloAmbiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                (
                    "ambiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocolos",
                        to="ambientes.ambiente",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambientes.tareaprotocolo",
                    ),
                ),
            ],
            options={
                "unique_together": {("ambiente", "tarea")},
            },
        ),
    ]
