# Generated by Django 4.2.7 on 2025-09-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
